name: Update site with latest commit

on:
  workflow_dispatch: ~
  push:
    branches:
      - main

jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger submodule update in site repo
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.SITE_REPO_PAT }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -d '{"event_type": "content-update"}' \
            https://api.github.com/repos/virain/virain.github.io/dispatches
