name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - v4
    repository_dispatch:
    types:
      - deploy
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for git info
          
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14

      - name: git config
        run: |
           git config --global user.email "xu_junkai@hotmail.com"
           git config --global user.name "virain"
          
      - name: add subtree content
        run: git subtree add --prefix=content https://github.com/virain/ob_document.git main
        
      - name: Update remote subtree
        run: git subtree pull --prefix=content https://github.com/virain/ob_document.git main --squash

      - name: Install Dependencies
        run: npm ci
        
      - name: Build Quartz
        run: npx quartz build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
