name: Update content

on:
  workflow_dispatch: ~
  repository_dispatch:
    types:
      - content-update

permissions:
  contents: write
  id-token: write

jobs:
  content-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v2

      - name: add subtree content
        run: git subtree add --prefix=content https://github.com/virain/ob_document.git main
      
      - name: Update remote subtree
        run: git subtree pull --prefix=content https://github.com/virain/ob_document.git main --squash
